### ISSUE TITLE
i3-desktop.patch

### ISSUE THREAD

**Issue by alessandro-g89** [ashinkarov/i3-extras#28]
Hi, I made a patch to support desktop windows with icons (i.e. with pcmanfm, nautilus and other file managers). It's based on i3 version 4.11.  Would you like to add it to the collection?
[i3-desktop.patch.zip](https://github.com/ashinkarov/i3-extras/files/118344/i3-desktop.patch.zip)

**Comment by ashinkarov** [comment]
Yeah, sure, why not.  Several questions though:

1. Have you ever tried to propose it to the official i3?
2. Do you want to write a short text on the usage of your patch?  The code looks like as if you apply the patch and then desktop managers just work.  But may be one should be aware of some subtle details.
3. Do you have a repository where you keep your patch (and possibly updates to it), or should we put it in i3-extras?

**Comment by alessandro-g89** [comment]
> Have you ever tried to propose it to the official i3?

[I did](https://github.com/i3/i3/issues/2189), but it was rejected because it does not fit into the tiling wm paradigm. I expected this kind of answer though.

> Do you want to write a short text on the usage of your patch? The code looks like as if you apply the patch and then desktop managers just work. But may be one should be aware of some subtle details.

It is my hope that it just works in most cases. However I wrote a short README.

> Do you have a repository where you keep your patch (and possibly updates to it), or should we put it in i3-extras?

If it's ok for you, we can put it in i3-extras and I'll send you updates if there are any. Maybe I'll start my own fork if/when I make some more tweaks.
[i3-desktop.patch.zip](https://github.com/ashinkarov/i3-extras/files/119013/i3-desktop.patch.zip)

**Comment by ashinkarov** [comment]
> I did, but it was rejected because it does not fit into the tiling wm paradigm. I expected this kind of answer though.

Right, I see; the tiling religion, isn't it :)

I'll add your patch to i3-extras later today.  Thanks for the contribution.

**Comment by ashinkarov** [comment]
Ok, I have added it, please see if it looks all right to you.  If it is, I will close this issue then.
If you'll have a newer version of will update a README, do a pull request.

**Comment by alessandro-g89** [comment]
Looks fine to me. Thanks for your support.
