### ISSUE TITLE
window-icons patch on i3-4.12, icon does not appear.

### ISSUE THREAD

**Issue by haobug** [ashinkarov/i3-extras#35]
because of solving a crash problem of scratchpad i upgraded to i3-4.12, 
managed to merge and install the [window-icons.patch](https://github.com/ashinkarov/i3-extras/tree/master/window-icons) to i3 version 4.12 with small tinkering.
[window-icons-4.12.patch.zip](https://github.com/ashinkarov/i3-extras/files/243061/window-icons-4.12.patch.zip)

**But the app icon does not appear**

**Comment by haobug** [comment]
i think the more important part might be here: 

```diff
--- window-icons.patch	2016-04-30 01:01:07.000000000 
+++ window-icons-4.12.patch	2016-04-30 03:14:52.000000000 
@@ -1,33 +1,33 @@
  /*
   * Draws the decoration of the given container onto its parent.
   *
-@@ -543,6 +584,9 @@ void x_draw_decoration(Con *con) {
+@@ -570,6 +611,9 @@ void x_draw_decoration(Con *con) {
  ...
 +#ifdef USE_ICONS
 +    /* Draw the icon */
 +    if (win->icon) {
 +        xcb_image_t* icon;
 +
 +        uint16_t width = 16;
 +        uint16_t height = 16;
 +        uint32_t icon_pixels[width*height];
 +
-+        copy_with_pixel_blend(icon_pixels, win->icon, p->color->background);
++        copy_with_pixel_blend(icon_pixels, win->icon, p->color->background.colorpixel);
 +
 +        icon = xcb_image_create_native( conn,
 +                width, height,
 +                XCB_IMAGE_FORMAT_Z_PIXMAP,
 +                root_depth,
 +                NULL,
@@ -35,23 +35,20 @@
 +                (uint8_t*)icon_pixels
 +                );
 +
 +        if (icon) {
 +            int icon_offset_y = (con->deco_rect.height - 16) / 2;
 +
-+            xcb_image_put(conn, parent->pixmap, parent->pm_gc,
++            xcb_image_put(conn, con->frame_buffer.id, con->frame_buffer.gc,
 +                    icon, con->deco_rect.x + indent_px - 16 , con->deco_rect.y + icon_offset_y, 0);
 +
 +            xcb_image_destroy(icon);
 +        }
 +        else {
 +            ELOG("Error creating XCB image\n");
 +        }
 +    }
 +#endif
 ```

**Comment by Airblader** [comment]
In the last change of that diff you are now placing the image onto the container's window, but previously it rendered it on the parent window.

Also, it's probably going to be an issue that you are just randomly making an XCB drawing call. You'll need to mark the cairo surface as dirty (see `libi3/draw_util.c`).

I really think a proper rebase of this patch will need to rewrite the patch quite a bit by properly introducing an abstraction function between XCB and cairo.

**Comment by haobug** [comment]
the window left-top corner looks like this 
![window_icon](https://cloud.githubusercontent.com/assets/1269309/14927939/848ffdf2-0e87-11e6-9554-462f874f90a9.png)

**Comment by haobug** [comment]
@Airblader i really don't know much about any of i3 cairo xcb. so i didn't understand all your idea.
i have had a looked at `libi3/draw_util.c` before i make that tinkering. 
there is no function for drawing icon like that can accept a icon parameter.

**Comment by Airblader** [comment]
> there is no function for drawing icon like that can accept a icon parameter.

Yes, there isn't. The rebased patch will have to introduce it.

**Comment by haobug** [comment]
> Yes, there isn't. The rebased patch will have to introduce it.

oh,,,,that will be a hard task for me. can i refer to the code to draw tray icon?

**Comment by Airblader** [comment]
No, because there is no "tray icon drawing" code. We don't draw tray icons, the application does that itself. We just reparent the window into i3bar.

There's currently no code in i3 that draws icons. You'd have to both learn a little about how cairo works and how `draw_util.c` works in i3.

**Comment by ashinkarov** [comment]
I think this has been resolved now.
