### ISSUE TITLE
interested in surface focus mode?  it neatly solves the stack/tab swamps problem

### ISSUE THREAD

**Issue by al-caveman** [ashinkarov/i3-extras#52]
patch solving the problem: https://github.com/i3/i3/pull/3859
description about the stack/tab swamp problem:  https://github.com/i3/i3/issues/3738

the patch adds the `surface` mode for `focus` command that allows navigating across stacks and tabs without shuffling them.  here is an example of my config that solves the stack/tabs swamp:
```
bindsym $mod+h focus left surface
bindsym $mod+j focus down surface
bindsym $mod+k focus up surface
bindsym $mod+l focus right surface
bindsym $mod+Mod1+h focus left
bindsym $mod+Mod1+j focus down
bindsym $mod+Mod1+k focus up
bindsym $mod+Mod1+l focus right
bindsym $mod+p focus prev sibling
bindsym $mod+n focus next sibling
```

a neat side effect of this is that stacks and tabs can now be treated just like tabs, except that stacks are tabs that are visually looking different than tabs.

i3 maintainers actually [liked it a lot](https://github.com/i3/i3/issues/3738#issuecomment-550185288), and also [approved the simplicity of the patch](https://github.com/i3/i3/pull/3859#issuecomment-593023090).  

but they ended up rejecting the patch simply because some guy named `squigz` lied to them about me about some irc drama, and they are ridiculously emotional and blindly trust rumours.  the guy `squigs` is actually blind, and he used to confuse me with another guy.  `squigs` actually banned me once thinking that i'm another, and snitched to ops of `#weechat` to ban me (but they refused since there were no reasons.  only the maintainers of i3 are dumb enough to obey him by believe him.  makes me wonder, who is more blind?

this could've easily ended up being in upstream i3, if not for `squigs`'s lies and the foolish upstream devs that blindly believe in rumours.

**Comment by ashinkarov** [comment]
Feel free to add a PR with the patch and a small description of what it is doing, what's the minimal version of i3 it has been tested with, etc.  Just follow the style of the `README.md`.
