### ISSUE TITLE
i3bar-xbm-icons.patch dose not worke with i3-4.8

### ISSUE THREAD

**Issue by Titzi90** [ashinkarov/i3-extras#9]
The version of the patch does not work with the new i3 version

**Comment by Titzi90** [comment]
Hi,
sorry if it was not clear what I wanted to say.

can you rebase it again to the new version (4.10.2).
Thank you.

**Comment by ashinkarov** [comment]
The commit @93a888c92a6c0de5c70c742e9a0fa03f9650affb fixes it.
